# Generated by Django 2.2.5 on 2019-09-06 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('img', models.ImageField(upload_to='gallery')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
